# MODEL

In [1]:
# Kütüphaneler

import pandas as pd
import numpy as np
from sklearn.linear_model import Ridge , Lasso , ElasticNet
from sklearn.metrics import mean_squared_error , r2_score
from sklearn.model_selection import train_test_split , cross_val_score
from sklearn import model_selection
import matplotlib.pyplot as plt
from sklearn.linear_model import RidgeCV , LassoCV , ElasticNetCV

    "x__ = " satırındaki "[["League_N" , "Division_W" , "NewLeague_N"]]" kısmını yazmasak ne olur? :

- "df" veri çerçevesi içindeki "League_N", "Division_W" ve "NewLeague_N" sütunlarını alarak "x__" veri çerçevesini oluşturduğunuzda, bu kodun amacı "dms" veri çerçevesinden bu üç sütunu alıp diğer bağımsız değişken sütunlarıyla birleştirmektir. Yani, "dms" veri çerçevesinin içerdiği ikili (dummy) değişken sütunlarını "x__" veri çerçevesi ile birleştirerek son bağımsız değişken veri çerçevesini oluşturuyorsunuz.

   Eğer "[["League_N" , "Division_W" , "NewLeague_N"]]" kısmını çıkartırsanız, "x__" veri çerçevesi "df" veri çerçevesinin sadece sayısal değerlere sahip sütunlarını içerecektir. Bu durumda, dummy değişkenlerinin yani "League_N", "Division_W" ve "NewLeague_N" sütunlarının modelin eğitimi ve performansı üzerindeki etkisi değerlendirilmemiş olur. Bu durumda, model dummy değişkenlerinin getirebileceği kategorik bilgileri kullanamaz ve bu da modelin doğruluğunu ve özelliklerini etkileyebilir.

   Sonuç olarak, eğer "[["League_N" , "Division_W" , "NewLeague_N"]]" kısmını çıkartırsanız, model dummy değişkenlerinin sağlayabileceği kategorik bilgileri kullanamayacaktır ve modelin performansı etkilenebilir.

In [14]:
df = pd.read_csv("C:\python_py\Makine Öğrenmesi-2\Hitters.csv")
df = df.dropna()

dms = pd.get_dummies(df[["League" , "Division" , "NewLeague"]])
y =  df["Salary"]
x__ = df.drop(["Salary" , "League" , "Division" , "NewLeague"] , axis=1).astype("float64")
x = pd.concat([x__ , dms[["League_N" , "Division_W" , "NewLeague_N"]]] , axis=1)
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size=0.25 , random_state=42)

In [15]:
# Modeli kuralım

enet_model = ElasticNet().fit(x_train , y_train)

C:\Users\Bedirhan Örseloğlu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.488e+06, tolerance: 3.899e+03
  model = cd_fast.enet_coordinate_descent(


In [16]:
enet_model.intercept_

-6.465955602112331

In [17]:
enet_model.coef_

array([ -1.86256172,   8.70489065,   5.10426375,  -2.89875799,
        -1.28642985,   5.24343682,   6.04480276,  -0.14701495,
        -0.21566628,  -0.7897201 ,   1.80813117,   0.80914508,
        -0.61262382,   0.26816203,   0.27172387,  -0.36530729,
        19.2186222 , -31.16586592,   8.98369938])

# TAHMİN

In [18]:
# Tahmin etme işlemi gerçekleştirelim

enet_model.predict(x_train)

array([ 325.74706292,  776.06632333,  522.86508419,  107.64091955,
        449.03139566,  997.76095723,   99.78828622,  311.33763086,
        418.50335021,  879.9502608 , 1628.05423879,  831.63172575,
        909.34196881,  715.67274292,  601.33595953,  657.40417507,
       1068.2110763 ,  149.6849625 ,  190.40513329,  385.31235163,
        752.37991572, 1022.76166475,  486.94874949,  349.7945189 ,
         69.28225147,  783.98489255,  551.11613877,  205.84644387,
        367.25234577,  303.22135065,   98.44933333,  533.19866378,
       1000.16419322,  245.20490159,  448.10920305,  401.93188524,
        457.71559572,  713.00914559,  333.18157434,  235.45584771,
        210.52615243,  309.20890759,  190.6560382 ,  183.01443111,
        238.19688018, 1080.44877923,  380.19569305,  551.45922356,
        278.3820838 ,  338.53829531,  427.9529666 ,  476.71228336,
        297.09609267,  435.8113557 ,  592.18850471,  320.60291497,
        510.97484699,  698.77992314,  218.04297483, 1535.95190

In [19]:
enet_model.predict(x_test)

array([ 577.79111731,  617.33202224, 1031.39113156,  364.95861575,
        489.51894393,  300.74185842,  604.522666  ,  465.34678732,
        901.44473965,  703.20357123,  702.9157117 ,  931.50283407,
        184.87939803,  385.14973787,  325.38944176,  546.99346574,
        774.28001821,  101.83114992, 1250.86758812,  370.67651244,
        442.05734523,  781.17288513,  578.63736538,  609.31927808,
        608.31719597,  227.46556223,  921.85505228,  301.1202457 ,
        386.31721051,  133.61143326,  162.28505608,   88.29793182,
        359.9068418 ,  422.51268445,  265.8663769 ,  355.70450908,
       1329.36312363,  125.05506935,   82.74580002,  269.17483075,
        117.13319397,  274.13484779,  648.4957249 ,  409.47065999,
        846.27919406,  712.04817644,  341.10596674,  368.24259678,
        305.70477656,  680.05724792,  716.13640636,  295.93204262,
        773.06445823,  249.28224916,  221.46794589,  541.2713245 ,
        611.50212372,  770.80228024,  168.45143906, 1159.05660

In [20]:
# Tahminler üzerinden hata oranımızı hesaplayalım

y_pred = enet_model.predict(x_test)

In [22]:
RMSE = np.sqrt(mean_squared_error(y_test , y_pred))
RMSE

357.1676548181246

In [23]:
# R2 skorunu inceleyelim (açıklanabilirlik yüzdesi)

r2_score(y_test , y_pred)

0.41070222469326867

# MODEL TUNİNG - DOĞRULAMA

In [24]:
# Cross Validation modelimizi kurduk.

enet_cv_model = ElasticNetCV(cv=10).fit(x_train , y_train)

In [25]:
enet_cv_model.alpha_    # optimum alfa (lambda) değeri

5230.764736479864

In [26]:
enet_cv_model.intercept_

-38.5194055839429

In [27]:
enet_cv_model.coef_

array([ 0.62845434,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -0.        ,  0.        ,  0.09788752,  0.        ,
        0.27265769,  0.19270075,  0.00758665,  0.3106529 ,  0.        ,
       -0.        ,  0.        , -0.        ,  0.        ])

In [28]:
# Bulduğumuz optimum alfa değeri ile final modelimizi oluşturalım

enet_tuned = ElasticNet(enet_cv_model.alpha_).fit(x_train , y_train)

In [37]:
# Final modelimizi kullanarak test setimiz için hata oranımızı bulalım

y_pred = enet_tuned.predict(x_test)
RMSE = np.sqrt(mean_squared_error(y_test , y_pred))
RMSE

394.15280563218795

- Önemli bir konu

In [38]:
?ElasticNet     # ElasticNet'in özelliklerine bir bakalım

Init signature:
ElasticNet(
    alpha=1.0,
    *,
    l1_ratio=0.5,
    fit_intercept=True,
    precompute=False,
    max_iter=1000,
    copy_X=True,
    tol=0.0001,
    warm_start=False,
    positive=False,
    random_state=None,
    selection='cyclic',
)
Docstring:     
Linear regression with combined L1 and L2 priors as regularizer.

Minimizes the objective function::

        1 / (2 * n_samples) * ||y - Xw||^2_2
        + alpha * l1_ratio * ||w||_1
        + 0.5 * alpha * (1 - l1_ratio) * ||w||^2_2

If you are interested in controlling the L1 and L2 penalty
separately, keep in mind that this is equivalent to::

        a * ||w||_1 + 0.5 * b * ||w||_2^2

where::

        alpha = a + b and l1_ratio = a / (a + b)

The parameter l1_ratio corresponds to alpha in the glmnet R package while
alpha corresponds to the lambda parameter in glmnet. Specifically, l1_ratio
= 1 is the lasso penalty. Currently, l1_ratio <= 0.01 is not reliable,
unless you supply your own sequence of alpha.

Read mo

- li1_ratio parametresi L1 (Lasso) ve L2(Ridge) arasındaki göreceli etkiyi ifade etmek için kullanılır. Nasıl ki alpha değeri için bir liste değeri verebiliyoruz (lambdalar1 = np.random.randint(0,1000,100)) l1_ratio parametresi için de verilebilir. Bu da her bir l1 değeri için farklı alphas değerleri oluşmasına neden olur. Bu durumda bu alfalar ceza terimleri etkilerini modele yansıtmış olacaktır.

- Burada aklımızda tutmamız gereken şey ElasticNet regresyonu modelinin Lasso ve Ridge'in etkilerini bir arada değerlendirdiği model kurma çalışmasıdır. İki tekniği birleştirmektedir. Bu iki tekniği birleştirdiğimizde iki tekniğin fonksiyonel yapı üzerindeki etkilerini kontrol edebilmek adına kullanılabilecek parametre de "li1_ratio" parametresidir. 

- Bu konuya özellikle burada giriyor olmamız ilerleye n bölümlerde doğrusal olmayan modellerde ele alacak olduğumuz birden fazla parametrenin birden fazla parametreyle olan kesişimleri ve göreceli etkilerine ilişkin kısa bir giriş yapmaktı. 